# Generated by Django 5.1.1 on 2024-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_name',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
