# Generated by Django 5.1.1 on 2024-10-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='posted_date',
            new_name='submission_date',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='due_date',
        ),
    ]
