# Generated by Django 5.1.1 on 2024-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_posted_date_assignments_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='grade_level',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
