# Generated by Django 5.1.1 on 2024-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='user_name',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
