# Generated by Django 5.1.1 on 2024-10-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_remove_student_first_name_remove_student_last_name_and_more'),
        ('teacher', '0003_remove_teacher_first_name_remove_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='conversation.questionanswer')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_questions', to='student.student')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_answers', to='teacher.teacher')),
            ],
        ),
    ]
