# Generated by Django 5.1.1 on 2024-10-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='parent',
            new_name='parent_id',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='is_question',
            field=models.BooleanField(default=True),
        ),
    ]
